
var sweety="Sweety";
var cutie="Cutie";
console.log("Before initialization :--->",sweety,cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("After initialization  :--->",sweety,cutie);
console.log("");
console.log("***************************************************************************");
console.log("");
var num1=100;
var num2=200;
var num3=300;
console.log("before initialization---->","num1:",num1,"   num2:",num2,"   num3:",num3);
var temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("After Initialization ---->","num1:",num1,"   num2:",num2,"   num3:",num3);